<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>SH2EESetup</RootNamespace>
		<AssemblyName>SH2EE.Core</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\config.xml" />
		<EmbeddedResource Include="Resources\component-files.csv" />
	</ItemGroup>

</Project>
