using System.Reflection;
using SH2EESetup.Models;

namespace SH2EESetup.Services
{
    /// <summary>One file shipped by a component, as recorded in the component map.</summary>
    public sealed record MappedFile(string Path, uint Crc32, long Size);

    /// <summary>Everything the map knows about one component.</summary>
    public sealed class MappedComponent
    {
        public required string Id { get; init; }
        public required string Name { get; init; }
        public required string Version { get; init; }
        public required string ArchiveFileName { get; init; }
        public required IReadOnlyList<MappedFile> Files { get; init; }
    }

    /// <summary>
    /// Which installed file came from which component, with upstream's own CRC-32 for each.
    ///
    /// Nothing in an installed game records this — SH2EEsetup.dat stores only which
    /// components are present, not what they put on disk — so without it an existing
    /// installation cannot be turned back into component archives.
    ///
    /// The map is generated by tools/refresh-component-map.py, which reads each archive's
    /// ZIP central directory over HTTP Range requests: the file list and per-file CRC-32 sit
    /// at the end of a ZIP, so it costs a few hundred KB rather than the ~4 GB the archives
    /// actually weigh. Regenerate it whenever upstream bumps a component version.
    /// </summary>
    public static class ComponentFileMap
    {
        private const string ResourceName = "SH2EESetup.Resources.component-files.csv";

        private static readonly Lazy<Dictionary<string, MappedComponent>> Components =
            new(Load, isThreadSafe: true);

        public static bool IsEmpty => Components.Value.Count == 0;

        public static MappedComponent? Get(string componentId) =>
            Components.Value.GetValueOrDefault(componentId);

        public static IEnumerable<MappedComponent> All => Components.Value.Values;

        /// <summary>
        /// The components in <paramref name="gameDir"/> that we can actually repackage: marked
        /// installed and present in the map. Anything else is reported to the user rather than
        /// silently dropped.
        /// </summary>
        public static List<MappedComponent> InstalledAndMapped(string gameDir) =>
            ManifestService.ReadInstalled(gameDir)
                .Where(c => c.IsInstalled && c.Id != ComponentIds.SetupTool)
                .Select(c => Get(c.Id))
                .Where(m => m != null)
                .Select(m => m!)
                .ToList();

        /// <summary>
        /// True when the installed version differs from the one the map was built against, so
        /// its file list may be missing entries or naming ones that no longer ship.
        /// </summary>
        public static bool IsVersionStale(string gameDir, MappedComponent mapped)
        {
            var installed = ManifestService.ReadInstalled(gameDir)
                .FirstOrDefault(c => string.Equals(c.Id, mapped.Id, StringComparison.OrdinalIgnoreCase));
            return installed != null &&
                   !string.Equals(installed.Version, mapped.Version, StringComparison.OrdinalIgnoreCase);
        }

        private static Dictionary<string, MappedComponent> Load()
        {
            var result = new Dictionary<string, MappedComponent>(StringComparer.OrdinalIgnoreCase);
            try
            {
                using var stream = Assembly.GetExecutingAssembly()
                    .GetManifestResourceStream(ResourceName);
                if (stream == null)
                    return result;

                using var reader = new StreamReader(stream);
                var files = new Dictionary<string, List<MappedFile>>(StringComparer.OrdinalIgnoreCase);
                var meta = new Dictionary<string, (string Name, string Version, string Archive)>(
                    StringComparer.OrdinalIgnoreCase);

                string? line;
                bool first = true;
                while ((line = reader.ReadLine()) != null)
                {
                    if (first) { first = false; continue; }   // header
                    if (line.Length == 0)
                        continue;

                    // componentId,componentName,componentVersion,archiveFileName,path,crc32,size
                    // Split with a limit: a component name may legitimately contain no comma
                    // today, but a path never contains one, so the tail is parsed from the right.
                    var cols = line.Split(',');
                    if (cols.Length < 7)
                        continue;

                    string id = cols[0];
                    string size = cols[^1];
                    string crc = cols[^2];
                    string path = string.Join(',', cols[4..^2]);
                    string archive = cols[3];
                    string version = cols[2];
                    string name = cols[1];

                    if (!uint.TryParse(crc, System.Globalization.NumberStyles.HexNumber,
                            null, out uint crcValue) ||
                        !long.TryParse(size, out long sizeValue))
                        continue;

                    if (!files.TryGetValue(id, out var list))
                        files[id] = list = new List<MappedFile>();
                    list.Add(new MappedFile(path.Replace('\\', '/'), crcValue, sizeValue));
                    meta[id] = (name, version, archive);
                }

                foreach (var (id, list) in files)
                {
                    var (name, version, archive) = meta[id];
                    result[id] = new MappedComponent
                    {
                        Id = id,
                        Name = name,
                        Version = version,
                        ArchiveFileName = archive,
                        Files = list,
                    };
                }
            }
            catch
            {
                // A missing or corrupt map disables repackaging; it must never break the app.
            }
            return result;
        }
    }
}
